<?php

use Drupal\user\Entity\User;

/**
 * Implements hook_install().
 */
function cmr_test_install() {
  // Create two users per role.
  User::create([
    'status' => TRUE,
    'name' => 'test drafter 1',
    'roles' => [
      'test_drafter',
    ],
  ])->save();
  User::create([
    'status' => TRUE,
    'name' => 'test drafter 2',
    'roles' => [
      'test_drafter',
    ],
  ])->save();
  User::create([
    'status' => TRUE,
    'name' => 'test editorial_reviewer 1',
    'roles' => [
      'test_editorial_reviewer',
    ],
  ])->save();
  User::create([
    'status' => TRUE,
    'name' => 'test editorial_reviewer 2',
    'roles' => [
      'test_editorial_reviewer',
    ],
  ])->save();
  User::create([
    'status' => TRUE,
    'name' => 'test legal_reviewer 1',
    'roles' => [
      'test_legal_reviewer',
    ],
  ])->save();
  User::create([
    'status' => TRUE,
    'name' => 'test legal_reviewer 2',
    'roles' => [
      'test_legal_reviewer',
    ],
  ])->save();
}
